# Generated by Django 2.1.5 on 2019-04-08 10:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ice_name', models.CharField(max_length=255, verbose_name='名称')),
                ('description', models.TextField(max_length=1000, null=True, verbose_name='説明')),
                ('price', models.CharField(max_length=255, verbose_name='価格')),
                ('amount', models.CharField(max_length=255, verbose_name='内容量')),
                ('image', models.CharField(max_length=255, verbose_name='商品画像')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日付')),
            ],
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker_name', models.CharField(max_length=255, verbose_name='メーカー')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日付')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.Maker', verbose_name='メーカー'),
        ),
    ]
